#goal definition
uint8 riser_diameter # millimeter
uint8 delta_angle
uint8 delta_height
uint8 vertical_number
uint8 horizontal_number
---
#result definition
float64[] latitude
float64[] longitude
float64[] altitude
---
#feedback
float64[] latitude
float64[] longitude
float64[] altitude